# Generated by Django 4.2.1 on 2023-05-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=20, verbose_name='Комментарий')),
                ('address', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('email', models.CharField(max_length=100, verbose_name='Комментарий')),
                ('date', models.CharField(max_length=20, verbose_name='Время')),
            ],
        ),
    ]
